#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CFLAGS =  -Wall

CFLAGS_RELEASE =  $(CFLAGS) -O2
OBJDIR_RELEASE = bin/
OUT_RELEASE = bin/gester

DESTDIR = /usr/local/bin/

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o

all: release

clean: clean_release

install:
	cp $(OUT_RELEASE) $(DESTDIR) 

before_release: 
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

release: before_release out_release

out_release: before_release $(OBJ_RELEASE)
	$(CXX) -o $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

clean_release: 
	rm -rf $(OBJDIR_RELEASE)/*

.PHONY: before_release clean_release

