#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CFLAGS =  -Wall -std=c++17

CFLAGS_RELEASE =  $(CFLAGS) -O2
OBJDIR_RELEASE = bin/
OUT_RELEASE = bin/gester

DEST_BINDIR = /usr/local/bin/
DEST_CONFDIR = /etc/gester/

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/evtest_utility.o $(OBJDIR_RELEASE)/ini_utility.o

all: release

clean: clean_release

install:
	mkdir -p $(DEST_CONFDIR)
	cp gester.conf $(DEST_CONFDIR)
	cp $(OUT_RELEASE) $(DEST_BINDIR) 

before_release: 
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

release: before_release out_release

out_release: before_release $(OBJ_RELEASE)
	$(CXX) -o $(OUT_RELEASE) $(OBJ_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/evtest_utility.o: evtest_utility.cpp
	$(CXX) $(CFLAGS_RELEASE) -c evtest_utility.cpp -o $(OBJDIR_RELEASE)/evtest_utility.o

$(OBJDIR_RELEASE)/ini_utility.o: ini_utility.cpp
	$(CXX) $(CFLAGS_RELEASE) -c ini_utility.cpp -o $(OBJDIR_RELEASE)/ini_utility.o

clean_release: 
	rm -rf $(OBJDIR_RELEASE)/*

.PHONY: before_release clean_release

